CN_project/CN_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('tickets/', include("ticketing.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CN_project/app1/urls.py
from django.urls import path
from . import views

app_name = 'app1'
urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    
    # ----------- management -----------
    path('login/', views.user_login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('admin_login/', views.admin_login, name='adminlogin'),
    path('admin_signup/', views.adminsignup, name='adminsignup'),
    path('logout/', views.user_logout, name='logout'),
    path('strike_resolving/<str:username>', views.strike_resolving, name='strike_resolving'),
    path('manager_login/', views.manager_login, name='manager_login'),
    
    # ----------- videos -----------
    path('upload/', views.upload_video, name='upload'),

    path('video/<int:video_id>/', views.watch_video, name='watch_video'), # with socket

    path('watch/<int:video_id>/', views.stream_video, name='stream_video'), # with html
    path('watch/<int:video_id>/f/', views.fstream, name='fstream'),
    path('watch/<int:video_id>/add_like/', views.add_like, name='add_like'),
    path('watch/<int:video_id>/add_dislike/', views.add_dislike, name='add_dislike'),
    path('watch/<int:video_id>/add_comment/', views.add_comment, name='add_comment'),

    path('video/add_lablel/', views.add_label, name='add_label'),
    path('video/make_unavailable/', views.video_status, name='status'),

]

CN_project/templates/login.html
<!DOCTYPE html>
<html lang="en">
<style>
    .login-container {
        padding: 44px;
        width: 400px;
        margin: 10% auto auto;
        background-color: #333333;
        border-radius: 8px;
        font-family: Roboto, serif;
    }

    input[type=text], input[type=password] {
        width: 100%;
        padding: 10px 10px;
        font-family: Roboto, serif;
        margin: 10px 0;
        background-color: #4d4d4d;
        display: inline-block;
        border: 1px solid #8c8c8c;
        border-radius: 8px;
        font-size: 16px;
        color: #ffffff;
        box-sizing: border-box;
    }
    .btn {
        background-color: #416dd9;
        color: white;
        padding: 14px 20px;
        font-size: 17px;
        margin: 8px 0;
        border: none;
        border-radius: 8px;
        cursor: pointer;
        width: 100%;
    }

</style>
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
{% if is_staff %}
    <body style="background-color:#0d1e4b;font-size: 20px;">
    <form class="login-container" action="{% url 'app1:adminlogin' %}" method="POST">

    <div style="text-align: center;color: #8d8d8d">Admin Login</div>
{% else %}
    <body style="background-color:#1c1c1c;font-size: 20px;">
    <form class="login-container" action="{% url 'app1:login' %}" method="POST">
{% endif %}
<label for="username" style="color: #a5bdf8"><b>Username</b>
    <input type="text" placeholder="Enter Username" name="username" required>
</label>
<label for="password" style="color: #9db2e5"><b>Password</b>
    <input type="password" placeholder="Enter Password" name="password" required>
</label>
{% if error_message %}
    <p style="color: red;font-size:17px">{{ error_message }}</p>
{% endif %}
<input name="login" type="submit" value="Login" class="btn btn-success"/>
</form>
</body>
</html>

CN_project/templates/video_view.html
<html lang="en">
<title>watching {{ video.title }}</title>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">

<style>
    .column {
        background-color: #171717;
        border-radius: 14px;
        margin-top: 10px;
        margin-bottom: 10px;
    }

    .video {
        width: 60%;
        float: left;
    }

    .cmnts {
        width: 38.5%;
        float: right;
    }

    textarea {
        resize: none;
        width: 100%;
        height: 60px;
        color: white;
        background-color: #000000;
        font-size: 16px;
        border-radius: 4px;
        border-color: #416dd9;
    }

    @media screen and (max-width: 900px) {
        .column {
            width: 100%;
        }
    }
</style>
<body style="background-color:#212121;">
<div class='container' style="font-family: Roboto, serif;padding: 10px;">
    <!-- VIDEO -->
    <div class="column video">
        <div class="wrapper" style="float:left;width: 100%">
            <!-- VIDEO PLAYER -->
            <div class="video-player" style="background-color: #000000;border-radius: 14px;float: left;width: 100%;">
                <video src="{{ video_url }}"
                       width=100%
                       height=60%
                       controls>
                </video>
            </div>
            <!-- VIDEO DETAILS + LIKE/DISLIKE BTN -->
            <div class="video-details" style="float:left;width: 100%;height: 100px;">
                <div class="video-info"
                     style="float:left;color:white;padding: 15px;height: 100%;box-sizing: border-box;">
                    <h><strong style="font-size:31px;">{{ video.title }}</strong>
                        {% if video.label == 'L' %}
                            &nbsp <a style="background-color:#de0000;border-radius: 7px;"> &nbsp warning &nbsp </a>
                        {% endif %}
                    </h>
                    <br>
                    <h style="font-size:21px;color:#e5e5e5;">{{ video.user }}
                        <small style="color:#6882c4"> — {{ video.pub_date }}</small>
                    </h>
                </div>
                <div class="video-votes"
                     style="float:right;padding: 30px 17px 17px;width:170px;height: 100%;box-sizing: border-box;">
                    <a id="like-button" class="votebtn fa fa-thumbs-up" type="button" title="I like this"
                       style="font-size: 30px;color: #888888;padding-right: 15px;">
                        <span id="likes_count">{{ video.like_count }}</span>
                    </a>
                    <a id="dislike-button" class="votebtn fa fa-thumbs-down" type="button" title="I dislike this"
                       style="font-size: 30px;color: #888888;">
                        <span id="dislikes_count">{{ video.dislike_count }}</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!------------    COMMENTS   ------------>
    <div class="column cmnts" style="color:#ffffff;background-color:#171717;border-radius:14px;">
        <div style="padding:6px;font-size:20px;text-align: center;
        border-radius:14px;">
            <strong> Comments </strong>
        </div>
        <div id="comment-container" style="padding:3px;font-size:20px;border-radius:14px;">
        </div>
        <div id="comment-form" style="padding:10px;border-radius:14px;">
            <label style="color:#b9b9b9;font-size:17px">add comment:<br>
                <textarea id="input-comment"> </textarea></label>
            <input type="submit" class="submitButton" id="comment-submit" value="post"
                   style="font-size:16px;background-color:#416dd9;color:#ffffff;float: right;border-radius:7px;">
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script type="text/javascript">
    function update_votes(user_vote, likes_count, dislikes_count) {
        $('#likes_count').html(likes_count);
        $('#dislikes_count').html(dislikes_count);
        $('#like-button').css('color', '#888888');
        $('#dislike-button').css('color', '#888888');
        if (user_vote === 'liked')
            $('#like-button').css('color', '#416dd9');
        else if (user_vote === 'disliked')
            $('#dislike-button').css('color', '#416dd9');
    }

    function vote_click(resp) {
        if (resp['update_error'] === undefined) {
            const user_vote = resp.update_data.user_vote;
            const likes_count = resp.update_data.likes_count;
            const dislikes_count = resp.update_data.dislikes_count;
            update_votes(user_vote, likes_count, dislikes_count);
        } else
            alert(resp.update_error.msg);
    }

    function create_comment(name, text) {
        if (text.length !== 0) {
            const new_comment = "<div class='comment-box' style='padding:4px;'>" +
                "<div class='comment-container' style='color:#ffffff;background-color:#252525;border-radius:10px;'>" +
                "<div class='comment-user' style='padding:10px 10px 8px;font-size:18px;'>" +
                "<b>" + name + "</b>" +
                "</div><div class='comment-text' style='padding: 0px 10px 8px;font-size:17px;overflow-wrap: break-word;'" +
                "<i>" + text + "</i>" +
                "</div></div></div>";
            $('#comment-container').append(new_comment);
        }
    }

    $('#like-button').click(function () {
        $.ajax({
            url: "{% url 'app1:add_like' video_id=video_id %}",
            type: 'get',
            dataType: 'JSON',
            success: function (response) {
                vote_click(response);
            }
        });
    });
    $('#dislike-button').click(function () {
        $.ajax({
            url: "{% url 'app1:add_dislike' video_id=video_id %}",
            type: 'get',
            dataType: 'JSON',
            success: function (response) {
                vote_click(response);
            }
        });
    });
    $('#comment-submit').click(function () {
        $.ajax({
            url: "{% url 'app1:add_comment' video_id=video_id %}",
            type: 'post',
            data: {comment: $('#input-comment').val()},
            success: function (response) {
                if (response['update_error'] === undefined) {
                    const name = response.update_data.cmn_username;
                    const text = response.update_data.cmn_text;
                    create_comment(name, text);
                } else
                    alert(response.update_error.msg);
                $('#input-comment').val('');
            }
        })
    });
    document.getElementById('input-comment').value = '';
    update_votes("{{ user_vote }}", "{{ video.like_count }}", "{{ video.dislike_count }}")
</script>
{% for comment in comments %}
    <script> create_comment("{{ comment.user }}", "{{ comment.comment }}"); </script>
{% endfor %}
</body>
</html>